import { 
  Empresa, 
  Usuario, 
  Cliente, 
  Negocio, 
  Projeto, 
  Contrato, 
  ItemOrcamento,
  OrdemProducao,
  RadarPrazosContrato,
  WhatsAppMessage,
  WhatsAppMetaConfig,
  InstalacaoAgendada,
  ContaReceber,
  ContaPagar,
  ComissaoRegistro,
  NotaFiscalDocumento,
  TicketAssistencia,
  MaterialEstoque,
  RegraPrecificacao
} from '@/types/database';

export const INITIAL_EMPRESAS: Empresa[] = [
  {
    id: 'emp_01',
    nomeFantasia: 'ArteForma Ambientes Planejados',
    razaoSocial: 'ArteForma Interiores & Marcenaria Fina Ltda',
    cnpj: '48.912.435/0001-89',
    inscricaoEstadual: '145.890.312.110',
    telefone: '(11) 3456-7890',
    email: 'contato@arteforma.com.br',
    cidade: 'São Paulo',
    uf: 'SP',
    enderecoCompleto: 'Av. das Nações Unidas, 14261 - Morumbi, São Paulo - SP',
    margemMinimaAceitavel: 22.0, // Trava da marcenaria: 22% de margem líquida mínima
    taxaCustoCapitalMensal: 1.8, // 1.8% a.m. para cálculo de VPL
    aliquotaImpostoPadrao: 6.5, // 6.5% Simples Nacional
    comissaoPadraoVendedor: 4.0, // 4.0%
    comissaoPadraoRT: 5.0, // 5.0% RT Arquiteto
    slaConfigPadrao: {
      diasMedidas: 3,
      diasRevisao: 2,
      diasPromobProjeto: 5,
      diasProducao: 20,
      diasMontagem: 5,
    },
    createdAt: '2026-01-10T10:00:00Z',
    updatedAt: '2026-01-10T10:00:00Z',
  },
  {
    id: 'emp_02',
    nomeFantasia: 'Studio Lux Marcenaria & Design',
    razaoSocial: 'Studio Lux Comércio de Móveis e Decoração Ltda',
    cnpj: '33.109.876/0001-45',
    inscricaoEstadual: '982.331.002.441',
    telefone: '(19) 3299-1122',
    email: 'atendimento@studioluxdesign.com.br',
    cidade: 'Campinas',
    uf: 'SP',
    enderecoCompleto: 'Rua Coronel Quirino, 850 - Cambuí, Campinas - SP',
    margemMinimaAceitavel: 25.0, // 25% margem mínima
    taxaCustoCapitalMensal: 2.0,
    aliquotaImpostoPadrao: 7.0,
    comissaoPadraoVendedor: 4.5,
    comissaoPadraoRT: 5.0,
    createdAt: '2026-02-01T14:30:00Z',
    updatedAt: '2026-02-01T14:30:00Z',
  }
];

export const INITIAL_USUARIOS: Usuario[] = [
  {
    id: 'usr_admin',
    nome: 'Carlos Eduardo Mendes',
    email: 'carlos.admin@arteforma.com.br',
    papel: 'administrador',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    telefone: '(11) 98765-4321',
    empresasIds: ['emp_01', 'emp_02'],
    empresaAtivaId: 'emp_01',
    cargoDescricao: 'Diretor Geral & Sócio',
    createdAt: '2026-01-10T10:00:00Z',
  },
  {
    id: 'usr_vendedor',
    nome: 'Juliana Castro',
    email: 'juliana.vendas@arteforma.com.br',
    papel: 'vendedor',
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    telefone: '(11) 97123-4567',
    empresasIds: ['emp_01'],
    empresaAtivaId: 'emp_01',
    cargoDescricao: 'Consultora de Vendas Sênior',
    createdAt: '2026-01-15T11:00:00Z',
  },
  {
    id: 'usr_projetista',
    nome: 'Lucas Silveira (Promob/3D)',
    email: 'lucas.projetos@arteforma.com.br',
    papel: 'projetista',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    telefone: '(11) 98334-5566',
    empresasIds: ['emp_01'],
    empresaAtivaId: 'emp_01',
    cargoDescricao: 'Arquiteto & Projetista 3D Especialista',
    createdAt: '2026-01-20T09:00:00Z',
  },
  {
    id: 'usr_producao',
    nome: 'Marcos Vinícius da Silva',
    email: 'marcos.fabrica@arteforma.com.br',
    papel: 'producao',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    telefone: '(11) 99887-1234',
    empresasIds: ['emp_01', 'emp_02'],
    empresaAtivaId: 'emp_01',
    cargoDescricao: 'Gerente de Produção Industrial',
    createdAt: '2026-01-22T08:00:00Z',
  },
  {
    id: 'usr_montador',
    nome: 'Rodrigo Barbosa (Montador)',
    email: 'rodrigo.montagem@arteforma.com.br',
    papel: 'montador',
    avatarUrl: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150&auto=format&fit=crop&q=80',
    telefone: '(11) 97654-9988',
    empresasIds: ['emp_01'],
    empresaAtivaId: 'emp_01',
    cargoDescricao: 'Líder de Montagem em Campo',
    createdAt: '2026-02-01T07:30:00Z',
  },
  {
    id: 'usr_financeiro',
    nome: 'Patrícia Alencar',
    email: 'patricia.financas@arteforma.com.br',
    papel: 'financeiro',
    avatarUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
    telefone: '(11) 99112-3344',
    empresasIds: ['emp_01', 'emp_02'],
    empresaAtivaId: 'emp_01',
    cargoDescricao: 'Controladoria & Contas a Receber',
    createdAt: '2026-01-12T10:00:00Z',
  }
];

export const INITIAL_CLIENTES: Cliente[] = [
  {
    id: 'cli_01',
    empresaId: 'emp_01',
    nome: 'Mariana Drummond e Silva',
    email: 'mariana.drummond@gmail.com',
    telefone: '(11) 98122-3344',
    whatsapp: '(11) 98122-3344',
    cpfCnpj: '234.567.890-12',
    origemLead: 'instagram',
    status: 'orcamento_enviado',
    endereco: {
      logradouro: 'Rua Bela Cintra',
      numero: '1850',
      complemento: 'Apto 142 - Bloco B',
      bairro: 'Consolação',
      cidade: 'São Paulo',
      uf: 'SP',
      cep: '01415-002',
    },
    observacoes: 'Apartamento novo de 120m². Deseja cozinha integrada, closet suíte master e painel ripado no living.',
    createdAt: '2026-02-05T11:20:00Z',
    updatedAt: '2026-02-12T15:00:00Z',
  },
  {
    id: 'cli_02',
    empresaId: 'emp_01',
    nome: 'Dr. Roberto Takahashi',
    email: 'roberto.takahashi@medclin.com.br',
    telefone: '(11) 97455-8899',
    whatsapp: '(11) 97455-8899',
    cpfCnpj: '345.678.901-23',
    origemLead: 'arquiteto',
    status: 'fechado',
    endereco: {
      logradouro: 'Alameda dos Maracatins',
      numero: '420',
      complemento: 'Conjunto 81',
      bairro: 'Moema',
      cidade: 'São Paulo',
      uf: 'SP',
      cep: '04089-011',
    },
    observacoes: 'Consultório médico de alto padrão. Móveis com acabamento acetinado antimicrobiano e iluminação LED embutida.',
    createdAt: '2026-01-18T14:10:00Z',
    updatedAt: '2026-02-10T16:45:00Z',
  },
  {
    id: 'cli_03',
    empresaId: 'emp_01',
    nome: 'Fernanda & Gabriel Vasconcellos',
    email: 'fernanda.vasc@hotmail.com',
    telefone: '(11) 99344-7711',
    whatsapp: '(11) 99344-7711',
    cpfCnpj: '456.789.012-34',
    origemLead: 'loja_fisica',
    status: 'em_atendimento',
    endereco: {
      logradouro: 'Rua Bento de Andrade',
      numero: '290',
      complemento: 'Casa',
      bairro: 'Jardim Paulista',
      cidade: 'São Paulo',
      uf: 'SP',
      cep: '04503-000',
    },
    observacoes: 'Casa inteira: Cozinha Gourmet, Área Externa, Lavanderia e 3 Quartos.',
    createdAt: '2026-02-10T10:00:00Z',
    updatedAt: '2026-02-14T09:30:00Z',
  },
  {
    id: 'cli_04',
    empresaId: 'emp_02',
    nome: 'Construtora Horizonte Verde',
    email: 'compras@horizonteverde.com.br',
    telefone: '(19) 3344-9000',
    whatsapp: '(19) 99881-2233',
    cpfCnpj: '12.345.678/0001-99',
    origemLead: 'indicacao',
    status: 'orcamento_enviado',
    endereco: {
      logradouro: 'Av. José de Souza Campos',
      numero: '1200',
      complemento: 'Sala 1502',
      bairro: 'Nova Campinas',
      cidade: 'Campinas',
      uf: 'SP',
      cep: '13025-320',
    },
    observacoes: 'Mobiliário completo para 4 decorados do novo empreendimento.',
    createdAt: '2026-02-01T08:00:00Z',
    updatedAt: '2026-02-12T11:00:00Z',
  }
];

export const INITIAL_NEGOCIOS: Negocio[] = [
  {
    id: 'neg_01',
    empresaId: 'emp_01',
    clienteId: 'cli_01',
    titulo: 'Apto Mariana Drummond - Cozinha + Living + Suíte Master',
    etapaFunil: 'apresentacao_orcamento',
    valorEstimado: 78500,
    scoreLead: 'quente',
    responsavelId: 'usr_vendedor',
    dataPrevisaoFechamento: '2026-02-28',
    createdAt: '2026-02-05T11:30:00Z',
    updatedAt: '2026-02-12T15:00:00Z',
  },
  {
    id: 'neg_02',
    empresaId: 'emp_01',
    clienteId: 'cli_02',
    titulo: 'Consultório Moema - Recepção + 2 Salas de Atendimento',
    etapaFunil: 'fechado_ganho',
    valorEstimado: 64200,
    scoreLead: 'quente',
    responsavelId: 'usr_vendedor',
    dataPrevisaoFechamento: '2026-02-10',
    createdAt: '2026-01-18T14:30:00Z',
    updatedAt: '2026-02-10T16:45:00Z',
  },
  {
    id: 'neg_03',
    empresaId: 'emp_01',
    clienteId: 'cli_03',
    titulo: 'Casa Jardim Paulista - Mobiliário Completo Alto Padrão',
    etapaFunil: 'projeto_3d',
    valorEstimado: 145000,
    scoreLead: 'morno',
    responsavelId: 'usr_vendedor',
    dataPrevisaoFechamento: '2026-03-15',
    createdAt: '2026-02-10T10:30:00Z',
    updatedAt: '2026-02-14T09:30:00Z',
  }
];

export const INITIAL_PROJETOS: Projeto[] = [
  {
    id: 'prj_01',
    empresaId: 'emp_01',
    negocioId: 'neg_01',
    clienteId: 'cli_01',
    nomeAmbiente: 'Cozinha Gourmet & Ilha Integrada',
    softwareOrigem: 'promob',
    arquivoNome: 'Drummond_Cozinha_v3.promob',
    versao: 'v3.2',
    statusProjeto: 'aguardando_aprovacao',
    observacoesTecnicas: 'MDF Carvalho Natural 18mm com frentes em Laca Cinza Fóssil fosca. Dobradiças com amortecimento Blum.',
    renderUrl: 'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?w=600&auto=format&fit=crop&q=80',
    valorCalculado: 48900,
    createdAt: '2026-02-08T10:00:00Z',
    updatedAt: '2026-02-12T14:00:00Z',
  },
  {
    id: 'prj_02',
    empresaId: 'emp_01',
    negocioId: 'neg_02',
    clienteId: 'cli_02',
    nomeAmbiente: 'Recepção e Balcão Curvo com LED',
    softwareOrigem: 'sketchup',
    arquivoNome: 'Clinica_Takahashi_Recepcao_Final.skp',
    versao: 'v2.0 (SketchUp 3D)',
    statusProjeto: 'aprovado_cliente',
    observacoesTecnicas: 'MDF Ultra resistente à umidade, tampo em Corian branco e fita LED 3000K com perfil embutido.',
    renderUrl: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=600&auto=format&fit=crop&q=80',
    valorCalculado: 64200,
    valorVendaDefinido: 64200,
    custoTotalPromob: 27800,
    modelo3dDados: {
      ambienteNome: 'Recepção e Balcão Curvo com LED',
      dimensoesGerais: {
        larguraTotalMm: 3600,
        alturaTotalMm: 2700,
        profundidadeTotalMm: 2400,
      },
      components: [
        {
          id: 'skp_comp_01',
          nome: 'Balcão de Atendimento Curvo com Corian',
          codigo: 'BAL-REC-01',
          ambiente: 'Recepção',
          dimensoes: { larguraMm: 2400, alturaMm: 1100, profundidadeMm: 750 },
          posicao: { x: 0, y: 550, z: 0 },
          material: 'MDF Ultra 18mm + Corian Glacier',
          cor: '#0284c7',
        },
        {
          id: 'skp_comp_02',
          nome: 'Painel Ripado de Fundo com LED 3000K',
          codigo: 'PAI-RIP-02',
          ambiente: 'Recepção',
          dimensoes: { larguraMm: 3400, alturaMm: 2600, profundidadeMm: 60 },
          posicao: { x: 0, y: 1300, z: -800 },
          material: 'MDF Carvalho Natural Ripado',
          cor: '#b45309',
        },
        {
          id: 'skp_comp_03',
          nome: 'Armário Alto com Portas de Vidro Reflecta',
          codigo: 'ARM-ALT-03',
          ambiente: 'Recepção',
          dimensoes: { larguraMm: 1200, alturaMm: 2100, profundidadeMm: 450 },
          posicao: { x: -1600, y: 1050, z: 200 },
          material: 'Perfil Alumínio Preto + Vidro Reflecta Bronze',
          cor: '#475569',
        }
      ]
    },
    createdAt: '2026-01-20T09:00:00Z',
    updatedAt: '2026-02-09T17:00:00Z',
  }
];

export const INITIAL_CONTRATOS: Contrato[] = [
  {
    id: 'ctr_01',
    empresaId: 'emp_01',
    negocioId: 'neg_02',
    clienteId: 'cli_02',
    projetoId: 'prj_02',
    numeroContrato: '#0042/2026',
    valorTotal: 64200,
    valorEntrada: 25680,
    condicoesPagamento: 'Entrada de 40% (R$ 25.680) + 3x de R$ 12.840 no boleto bancário pós-medição fina',
    statusAssinatura: 'assinado',
    dataAssinatura: '2026-02-10',
    prazoEntregaDias: 45,
    prazoMontagemDias: 7,
    dataPrevistaEntrega: '2026-03-27',
    garantiaAnos: 5,
    tokenAssinaturaCliente: 'sig_mock_42',
    linkAssinaturaCliente: 'https://erp-planejados.app/assinar/sig_mock_42',
    assinaturaEmpresa: {
      assinado: true,
      dataAssinatura: '2026-02-09T18:30:00Z',
      assinanteNome: 'Carlos Eduardo Silveira',
      assinanteCargo: 'Diretor Comercial & Sócio',
      certificadoNome: 'Marcenaria Arte & Forma Interiores Ltda',
      certificadoCnpj: '12.345.678/0001-90',
      autoridadeCertificadora: 'AC SOLUTI Multipla v5 • ICP-Brasil',
      numeroSerie: '7A9F.4B12.C830.5901.D3',
      hashSha256: '9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a08',
      carimboTempoIcp: '2026-02-09T18:30:15-03:00 (ACT Soluti Carimbo do Tempo)',
    },
    assinaturaCliente: {
      assinado: true,
      dataAssinatura: '2026-02-10T16:45:00Z',
      nomeCompleto: 'Dr. Roberto Almeida',
      cpfCnpj: '123.456.789-00',
      email: 'roberto.almeida@cardio.med.br',
      telefone: '(11) 97777-8888',
      ip: '189.40.122.54 (São Paulo - SP)',
      dispositivo: 'iPhone 15 Pro • Safari 17.4 (iOS 17.4)',
      hashSha256: '5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8',
      termoAceiteTexto: 'Aceito integralmente as cláusulas deste contrato de fabricação sob medida.',
    },
    itensDescritivos: [
      { ambiente: 'Suíte Master', descricao: 'Closet Casal em MDF Louro Freijó com iluminação LED embutida', quantidade: 1, valor: 42000 },
      { ambiente: 'Home Theater', descricao: 'Painel Ripado com Rack Suspenso e Gavetas com fecho-toque', quantidade: 1, valor: 22200 }
    ],
    logAuditoria: [
      {
        id: 'log_01',
        timestamp: '2026-02-09T16:00:00Z',
        evento: 'contrato_gerado',
        ator: 'Carlos Silveira (Vendas)',
        detalhes: 'Contrato gerado automaticamente com numeração #0042/2026',
      },
      {
        id: 'log_02',
        timestamp: '2026-02-09T18:30:00Z',
        evento: 'assinado_icp_brasil_empresa',
        ator: 'Marcenaria Arte & Forma Ltda (e-CNPJ A1)',
        detalhes: 'Assinatura digital ICP-Brasil aplicada com sucesso',
      },
      {
        id: 'log_03',
        timestamp: '2026-02-10T16:45:00Z',
        evento: 'assinado_eletronicamente_cliente',
        ator: 'Dr. Roberto Almeida',
        detalhes: 'Assinatura eletrônica com IP e rubrica registrada',
      }
    ],
    arquivoContratoUrl: '/docs/contratos/ctr_0042_2026.pdf',
    createdAt: '2026-02-09T16:00:00Z',
    updatedAt: '2026-02-10T16:45:00Z',
  },
  {
    id: 'ctr_02',
    empresaId: 'emp_01',
    negocioId: 'neg_01',
    clienteId: 'cli_01',
    projetoId: 'prj_01',
    numeroContrato: '#0043/2026',
    valorTotal: 78500,
    valorEntrada: 23550,
    condicoesPagamento: 'Entrada 30% no ato + 5x sem juros no cartão',
    statusAssinatura: 'aguardando_assinatura_cliente',
    prazoEntregaDias: 40,
    prazoMontagemDias: 7,
    dataPrevistaEntrega: '2026-04-10',
    garantiaAnos: 5,
    tokenAssinaturaCliente: 'sig_mock_43',
    linkAssinaturaCliente: 'https://erp-planejados.app/assinar/sig_mock_43',
    assinaturaEmpresa: {
      assinado: true,
      dataAssinatura: '2026-02-12T15:30:00Z',
      assinanteNome: 'Carlos Eduardo Silveira',
      assinanteCargo: 'Diretor Comercial',
      certificadoNome: 'Marcenaria Arte & Forma Interiores Ltda',
      certificadoCnpj: '12.345.678/0001-90',
      autoridadeCertificadora: 'AC SOLUTI Multipla v5 • ICP-Brasil',
      numeroSerie: '7A9F.4B12.C830.5901.D3',
      hashSha256: 'b45cffe084dd3d20d928bee85e7b0f21',
    },
    itensDescritivos: [
      { ambiente: 'Cozinha Gourmet', descricao: 'Armários planejados em MDF Grafite Tx com perfil gola preto', quantidade: 1, valor: 48500 },
      { ambiente: 'Lavanderia', descricao: 'Módulos suspensos com nicho para máquina lava e seca', quantidade: 1, valor: 30000 }
    ],
    logAuditoria: [
      {
        id: 'log_04',
        timestamp: '2026-02-12T15:00:00Z',
        evento: 'contrato_gerado',
        ator: 'Sistema ERP',
        detalhes: 'Contrato gerado a partir da negociação com margem de 26.5%',
      },
      {
        id: 'log_05',
        timestamp: '2026-02-12T15:30:00Z',
        evento: 'assinado_icp_brasil_empresa',
        ator: 'Carlos Silveira (e-CNPJ A1)',
        detalhes: 'Assinatura digital ICP-Brasil realizada. Link enviado ao cliente via WhatsApp.',
      }
    ],
    createdAt: '2026-02-12T15:30:00Z',
    updatedAt: '2026-02-12T15:30:00Z',
  }
];

export const INITIAL_ITENS_ORCAMENTO: ItemOrcamento[] = [
  {
    id: 'itm_01',
    empresaId: 'emp_01',
    projetoId: 'prj_01',
    codigo: 'ARM-INF-COZ-01',
    descricao: 'Módulo Inferior Pia com 2 Gavetões e 1 Gaveta Oculta porta-talheres',
    ambiente: 'Cozinha Gourmet',
    medidas: {
      larguraMm: 1200,
      alturaMm: 780,
      profundidadeMm: 600,
    },
    material: 'MDF Naval 18mm Branco Tx (Interno)',
    acabamento: 'Laca Cinza Fóssil Acetinada (Frentes)',
    quantidade: 1,
    custoUnitario: 1450,
    precoVenda: 3200,
    margemLucroPercent: 54.7,
    createdAt: '2026-02-08T10:15:00Z',
  },
  {
    id: 'itm_02',
    empresaId: 'emp_01',
    projetoId: 'prj_01',
    codigo: 'TOR-FOR-COZ-02',
    descricao: 'Torre Quente para Forno Embutido + Micro-ondas com nicho superior basculante',
    ambiente: 'Cozinha Gourmet',
    medidas: {
      larguraMm: 700,
      alturaMm: 2400,
      profundidadeMm: 600,
    },
    material: 'MDF 18mm Carvalho Natural',
    acabamento: 'Madeirado com Veios Contínuos',
    quantidade: 1,
    custoUnitario: 2100,
    precoVenda: 4850,
    margemLucroPercent: 56.7,
    createdAt: '2026-02-08T10:30:00Z',
  },
  {
    id: 'itm_03',
    empresaId: 'emp_01',
    projetoId: 'prj_02',
    codigo: 'BAL-REC-01',
    descricao: 'Balcão de Atendimento Curvo com estrutura reforçada e calha para fiação',
    ambiente: 'Recepção',
    medidas: {
      larguraMm: 2400,
      alturaMm: 1100,
      profundidadeMm: 750,
    },
    material: 'MDF Ultra 18mm + Estrutura de Aço',
    acabamento: 'Painel Ripado Carvalho + Corian Branco Glacier',
    quantidade: 1,
    custoUnitario: 8900,
    precoVenda: 19800,
    margemLucroPercent: 55.0,
    createdAt: '2026-01-20T09:45:00Z',
  }
];

export const INITIAL_ORDENS_PRODUCAO: OrdemProducao[] = [
  {
    id: 'op_01',
    empresaId: 'emp_01',
    negocioId: 'neg_02',
    clienteId: 'cli_02',
    clienteNome: 'Dr. Roberto Almeida',
    contratoId: 'ctr_01',
    numeroContrato: '#0042/2026',
    projetoId: 'prj_02',
    numeroOP: 'OP-#0042/2026',
    titulo: 'Consultório Moema - Suíte Master & Closet',
    etapaAtual: 'corte',
    prioridade: 'alta',
    prazoDias: 45,
    dataInicio: '2026-02-10T17:00:00Z',
    dataPrevisaoEntrega: '2026-03-27T18:00:00Z',
    totalPecas: 54,
    totalChapasMdf: 9,
    ambientes: ['Suíte Master', 'Closet Casal', 'Home Theater'],
    responsavelAtualNome: 'Marcos Vinícius (Seccionadora CNC)',
    historicoTransicoes: [
      {
        id: 'trans_01',
        etapa: 'fila_producao',
        dataEntrada: '2026-02-10T17:00:00Z',
        dataConclusao: '2026-02-11T09:30:00Z',
        responsavelNome: 'Carlos Eduardo Silveira (PCP)',
        proximoResponsavelNome: 'Marcos Vinícius (Seccionadora CNC)',
        observacoes: 'Chapas MDF Louro Freijó e Grafite Tx conferidas e liberadas para corte.',
        checklistConcluido: true
      },
      {
        id: 'trans_02',
        etapa: 'corte',
        dataEntrada: '2026-02-11T09:30:00Z',
        responsavelNome: 'Marcos Vinícius (Seccionadora CNC)',
        observacoes: 'Otimização de corte com 91.4% de aproveitamento de chapa. 32/54 peças cortadas.',
        checklistConcluido: false
      }
    ],
    observacoes: 'MDF Louro Freijó 18mm + MDF Grafite Tx. Atenção para veios horizontais contínuos nas portas.',
    createdAt: '2026-02-10T17:00:00Z',
    updatedAt: '2026-02-11T09:30:00Z',
  },
  {
    id: 'op_02',
    empresaId: 'emp_01',
    negocioId: 'neg_01',
    clienteId: 'cli_01',
    clienteNome: 'Mariana Drummond',
    contratoId: 'ctr_02',
    numeroContrato: '#0043/2026',
    projetoId: 'prj_01',
    numeroOP: 'OP-#0043/2026',
    titulo: 'Apto Bela Cintra - Cozinha Gourmet & Lavanderia',
    etapaAtual: 'fila_producao',
    prioridade: 'normal',
    prazoDias: 40,
    dataInicio: '2026-02-12T15:30:00Z',
    dataPrevisaoEntrega: '2026-04-10T18:00:00Z',
    totalPecas: 38,
    totalChapasMdf: 6,
    ambientes: ['Cozinha Gourmet', 'Lavanderia'],
    responsavelAtualNome: 'Programador PCP Fábrica',
    historicoTransicoes: [
      {
        id: 'trans_03',
        etapa: 'fila_producao',
        dataEntrada: '2026-02-12T15:30:00Z',
        responsavelNome: 'Programador PCP Fábrica',
        observacoes: 'Ordem de produção criada automaticamente após assinatura do contrato #0043/2026.',
        checklistConcluido: false
      }
    ],
    observacoes: 'Perfil gola preto e corrediças ocultas com amortecimento. Aguardando medição fina.',
    createdAt: '2026-02-12T15:30:00Z',
    updatedAt: '2026-02-12T15:30:00Z',
  }
];

export const INITIAL_RADARES_PRAZOS: RadarPrazosContrato[] = [
  {
    id: 'rdr_ctr_01',
    empresaId: 'emp_01',
    contratoId: 'ctr_01',
    numeroContrato: '#0042/2026',
    clienteId: 'cli_02',
    clienteNome: 'Dr. Roberto Almeida',
    tituloProjeto: 'Consultório Moema - Suíte Master & Recepção',
    valorContrato: 64200,
    dataAssinaturaContrato: '2026-02-10T16:45:00Z',
    dataPrevisaoEntregaFinal: '2026-03-27T18:00:00Z',
    marcoAtual: 'producao',
    statusGeralAlerta: 'verde',
    diasTotaisSla: 35,
    diasDecorridosTotais: 6,
    marcos: [
      {
        tipo: 'medidas',
        nome: 'Medição Fina no Local',
        descricao: 'Conferência milimétrica in-loco de paredes e pontos elétricos.',
        slaDias: 3,
        dataInicioPrevista: '2026-02-10T17:00:00Z',
        dataLimitePrevista: '2026-02-13T17:00:00Z',
        dataConclusaoReal: '2026-02-11T14:20:00Z',
        statusMarco: 'concluido',
        statusAlerta: 'verde',
        diasRestantes: 0,
        percentualTempoDecorrido: 100,
        responsavelNome: 'Lucas Medições Técnicas',
        observacoes: 'Medidas 100% conferidas. Nenhuma divergência de prumo ou esquadro.'
      },
      {
        tipo: 'revisao',
        nome: 'Revisão Técnica & Detalhes',
        descricao: 'Compatibilização com o projeto executivo e alinhamento.',
        slaDias: 2,
        dataInicioPrevista: '2026-02-11T14:20:00Z',
        dataLimitePrevista: '2026-02-13T14:20:00Z',
        dataConclusaoReal: '2026-02-12T11:00:00Z',
        statusMarco: 'concluido',
        statusAlerta: 'verde',
        diasRestantes: 0,
        percentualTempoDecorrido: 100,
        responsavelNome: 'Arq. Camila Esteves',
        observacoes: 'Ajuste de 15mm no painel ripado para encaixe do interruptor.'
      },
      {
        tipo: 'promob_projeto',
        nome: 'Engenharia Promob / Projeto 3D',
        descricao: 'Geração dos planos de corte e furação CNC.',
        slaDias: 5,
        dataInicioPrevista: '2026-02-12T11:00:00Z',
        dataLimitePrevista: '2026-02-17T11:00:00Z',
        dataConclusaoReal: '2026-02-14T16:00:00Z',
        statusMarco: 'concluido',
        statusAlerta: 'verde',
        diasRestantes: 0,
        percentualTempoDecorrido: 100,
        responsavelNome: 'Eng. Renato Promob',
        observacoes: 'Arquivos .xml e .gcode exportados diretamente para a seccionadora.'
      },
      {
        tipo: 'producao',
        nome: 'Produção Fabril (Chão de Fábrica)',
        descricao: 'Corte, usinagem, fita de borda, montagem de gavetas e embalagem.',
        slaDias: 18,
        dataInicioPrevista: '2026-02-14T16:00:00Z',
        dataLimitePrevista: '2026-03-04T16:00:00Z',
        statusMarco: 'em_andamento',
        statusAlerta: 'verde',
        diasRestantes: 16,
        percentualTempoDecorrido: 12,
        responsavelNome: 'Gerente Fabril ArteForma',
        observacoes: 'Ordem de Produção OP-#0042/2026 em andamento na etapa de Corte CNC.'
      },
      {
        tipo: 'montagem',
        nome: 'Montagem no Cliente',
        descricao: 'Instalação física dos móveis planejados na obra.',
        slaDias: 6,
        dataInicioPrevista: '2026-03-05T08:00:00Z',
        dataLimitePrevista: '2026-03-11T18:00:00Z',
        statusMarco: 'pendente',
        statusAlerta: 'verde',
        diasRestantes: 23,
        percentualTempoDecorrido: 0,
        responsavelNome: 'Equipe de Montagem Alpha'
      },
      {
        tipo: 'concluido',
        nome: 'Concluído (Vistoria & Aceite)',
        descricao: 'Vistoria final com o cliente e assinatura do termo de entrega.',
        slaDias: 1,
        dataInicioPrevista: '2026-03-12T09:00:00Z',
        dataLimitePrevista: '2026-03-12T18:00:00Z',
        statusMarco: 'pendente',
        statusAlerta: 'verde',
        diasRestantes: 24,
        percentualTempoDecorrido: 0,
        responsavelNome: 'Carlos Silveira (Pós-Venda)'
      }
    ],
    createdAt: '2026-02-10T17:00:00Z',
    updatedAt: '2026-02-14T16:00:00Z'
  },
  {
    id: 'rdr_ctr_02',
    empresaId: 'emp_01',
    contratoId: 'ctr_02',
    numeroContrato: '#0043/2026',
    clienteId: 'cli_01',
    clienteNome: 'Mariana Drummond',
    tituloProjeto: 'Apto Bela Cintra - Cozinha Gourmet & Lavanderia',
    valorContrato: 78500,
    dataAssinaturaContrato: '2026-02-12T15:30:00Z',
    dataPrevisaoEntregaFinal: '2026-04-10T18:00:00Z',
    marcoAtual: 'medidas',
    statusGeralAlerta: 'amarelo',
    diasTotaisSla: 35,
    diasDecorridosTotais: 3,
    marcos: [
      {
        tipo: 'medidas',
        nome: 'Medição Fina no Local',
        descricao: 'Conferência milimétrica in-loco de paredes e pontos elétricos.',
        slaDias: 3,
        dataInicioPrevista: '2026-02-12T16:00:00Z',
        dataLimitePrevista: '2026-02-17T18:00:00Z',
        statusMarco: 'em_andamento',
        statusAlerta: 'amarelo',
        diasRestantes: 1,
        percentualTempoDecorrido: 85,
        responsavelNome: 'Lucas Medições Técnicas',
        observacoes: 'Aguardando liberação de acesso na portaria do condomínio na Bela Cintra.'
      },
      {
        tipo: 'revisao',
        nome: 'Revisão Técnica & Detalhes',
        descricao: 'Compatibilização com o projeto executivo e alinhamento.',
        slaDias: 2,
        dataInicioPrevista: '2026-02-18T08:00:00Z',
        dataLimitePrevista: '2026-02-20T18:00:00Z',
        statusMarco: 'pendente',
        statusAlerta: 'verde',
        diasRestantes: 4,
        percentualTempoDecorrido: 0,
        responsavelNome: 'Projetista Responsável'
      },
      {
        tipo: 'promob_projeto',
        nome: 'Engenharia Promob / Projeto 3D',
        descricao: 'Geração dos planos de corte e furação CNC.',
        slaDias: 5,
        dataInicioPrevista: '2026-02-21T08:00:00Z',
        dataLimitePrevista: '2026-02-26T18:00:00Z',
        statusMarco: 'pendente',
        statusAlerta: 'verde',
        diasRestantes: 10,
        percentualTempoDecorrido: 0,
        responsavelNome: 'Engenheiro de Produto'
      },
      {
        tipo: 'producao',
        nome: 'Produção Fabril (Chão de Fábrica)',
        descricao: 'Corte, usinagem, fita de borda, montagem de gavetas e embalagem.',
        slaDias: 18,
        dataInicioPrevista: '2026-02-27T08:00:00Z',
        dataLimitePrevista: '2026-03-20T18:00:00Z',
        statusMarco: 'pendente',
        statusAlerta: 'verde',
        diasRestantes: 32,
        percentualTempoDecorrido: 0,
        responsavelNome: 'Gerente Fabril'
      },
      {
        tipo: 'montagem',
        nome: 'Montagem no Cliente',
        descricao: 'Instalação física dos móveis planejados na obra.',
        slaDias: 6,
        dataInicioPrevista: '2026-03-21T08:00:00Z',
        dataLimitePrevista: '2026-03-27T18:00:00Z',
        statusMarco: 'pendente',
        statusAlerta: 'verde',
        diasRestantes: 39,
        percentualTempoDecorrido: 0,
        responsavelNome: 'Equipe de Montagem'
      },
      {
        tipo: 'concluido',
        nome: 'Concluído (Vistoria & Aceite)',
        descricao: 'Vistoria final com o cliente e assinatura do termo de entrega.',
        slaDias: 1,
        dataInicioPrevista: '2026-03-28T09:00:00Z',
        dataLimitePrevista: '2026-03-28T18:00:00Z',
        statusMarco: 'pendente',
        statusAlerta: 'verde',
        diasRestantes: 40,
        percentualTempoDecorrido: 0,
        responsavelNome: 'Pós-Venda'
      }
    ],
    createdAt: '2026-02-12T15:30:00Z',
    updatedAt: '2026-02-15T10:00:00Z'
  }
];

export const INITIAL_WHATSAPP_MESSAGES: WhatsAppMessage[] = [
  {
    id: 'wmsg_01',
    empresaId: 'emp_01',
    telefone: '(11) 98122-3344',
    clienteId: 'cli_01',
    negocioId: 'neg_01',
    direcao: 'entrada',
    texto: 'Olá, vi as fotos dos projetos de cozinha no Instagram da ArteForma! Gostaria de agendar um orçamento para meu apartamento na Bela Cintra.',
    timestamp: '2026-02-15T09:12:00Z',
    status: 'lida',
    lida: true,
    autorNome: 'Mariana Drummond',
  },
  {
    id: 'wmsg_02',
    empresaId: 'emp_01',
    telefone: '(11) 98122-3344',
    clienteId: 'cli_01',
    negocioId: 'neg_01',
    direcao: 'saida',
    texto: 'Olá Mariana! Será um enorme prazer planejar seu espaço. Você já possui a planta baixa ou prefere que nosso projetista vá até o local para a medição técnica?',
    timestamp: '2026-02-15T09:16:00Z',
    status: 'lida',
    lida: true,
    autorNome: 'Juliana Castro (Consultora)',
  },
  {
    id: 'wmsg_03',
    empresaId: 'emp_01',
    telefone: '(11) 98122-3344',
    clienteId: 'cli_01',
    negocioId: 'neg_01',
    direcao: 'entrada',
    texto: 'Perfeito! Gostaria da visita técnica para conferir o vão da geladeira e a ilha com cooktop.',
    timestamp: '2026-02-15T09:20:00Z',
    status: 'lida',
    lida: true,
    autorNome: 'Mariana Drummond',
  },
  {
    id: 'wmsg_04',
    empresaId: 'emp_01',
    telefone: '(11) 98122-3344',
    clienteId: 'cli_01',
    negocioId: 'neg_01',
    direcao: 'saida',
    texto: 'Combinado! Acabei de disponibilizar seu projeto 3D no sistema. Vou te enviar a prévia dos renders em breve!',
    timestamp: '2026-02-15T11:45:00Z',
    status: 'entregue',
    lida: true,
    autorNome: 'Juliana Castro (Consultora)',
  },
  {
    id: 'wmsg_05',
    empresaId: 'emp_01',
    telefone: '(11) 98122-3344',
    clienteId: 'cli_01',
    negocioId: 'neg_01',
    direcao: 'entrada',
    texto: 'Adorei os tons de cinza fóssil e carvalho natural! Quando podemos fechar as condições de pagamento?',
    timestamp: '2026-02-16T08:10:00Z',
    status: 'entregue',
    lida: false, // Não lida intencionalmente para teste visual
    autorNome: 'Mariana Drummond',
  },
  {
    id: 'wmsg_06',
    empresaId: 'emp_01',
    telefone: '(11) 97455-8899',
    clienteId: 'cli_02',
    negocioId: 'neg_02',
    direcao: 'entrada',
    texto: 'Boa tarde Juliana! O contrato do consultório já foi assinado digitalmente.',
    timestamp: '2026-02-10T16:50:00Z',
    status: 'lida',
    lida: true,
    autorNome: 'Dr. Roberto Takahashi',
  },
  {
    id: 'wmsg_07',
    empresaId: 'emp_01',
    telefone: '(11) 97455-8899',
    clienteId: 'cli_02',
    negocioId: 'neg_02',
    direcao: 'saida',
    texto: 'Confirmado Dr. Roberto! Ordem de produção nº #0042 já enviada para a fábrica.',
    timestamp: '2026-02-10T17:02:00Z',
    status: 'lida',
    lida: true,
    autorNome: 'Juliana Castro (Consultora)',
  },
  {
    id: 'wmsg_08',
    empresaId: 'emp_01',
    telefone: '(11) 99344-7711',
    clienteId: 'cli_03',
    negocioId: 'neg_03',
    direcao: 'entrada',
    texto: 'Oi Juliana! Conseguem incluir a marcenaria do closet da suíte 2 no mesmo orçamento da casa do Jardim Paulista?',
    timestamp: '2026-02-16T07:45:00Z',
    status: 'entregue',
    lida: false, // Mensagem recente não lida
    autorNome: 'Fernanda & Gabriel',
  },
  {
    id: 'wmsg_09',
    empresaId: 'emp_01',
    telefone: '(11) 96555-1122', // Novo número que não está no CRM inicial para teste de auto-criação de lead!
    direcao: 'entrada',
    texto: 'Olá! Peguei a indicação de vocês com o arquiteto Bruno. Gostaria de saber valores médios para mobiliar um duplex novo no Itaim.',
    timestamp: '2026-02-16T08:05:00Z',
    status: 'entregue',
    lida: false,
    autorNome: 'Helena Montenegro (Novo Contato)',
  }
];

export const INITIAL_META_CONFIG: WhatsAppMetaConfig = {
  phoneNumberId: '',
  wabaId: '',
  accessToken: '',
  verifyToken: 'mobplan_marcenaria_verify_secret_2026',
  webhookUrl: '/api/whatsapp/webhook',
  status: 'pendente_configuracao',
};

export const INITIAL_INSTALACOES: InstalacaoAgendada[] = [
  {
    id: 'inst_01',
    empresaId: 'emp_01',
    contratoId: 'ctr_01',
    numeroContrato: '#0042/2026',
    clienteId: 'cli_01',
    clienteNome: 'Mariana Drummond e Silva',
    enderecoInstalacao: {
      logradouro: 'Rua Bela Cintra',
      numero: '1240',
      complemento: 'Apt 82',
      bairro: 'Cerqueira César',
      cidade: 'São Paulo',
      uf: 'SP',
      cep: '01415-001'
    },
    dataHoraAgendamento: '2026-02-18T09:00:00Z',
    montadorId: 'usr_montador',
    montadorNome: 'Rodrigo Barbosa (Montador)',
    status: 'agendada',
    fotos: [
      {
        id: 'foto_01',
        url: 'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=800&auto=format&fit=crop&q=80',
        tipo: 'antes',
        timestamp: '2026-02-18T09:15:00Z',
        autorNome: 'Rodrigo Barbosa'
      }
    ],
    checklist: [
      { id: 'chk_1', titulo: 'Conferência de volumes e integridade dos MDFs', concluido: true, categoria: 'Conferência' },
      { id: 'chk_2', titulo: 'Nivelamento de caixaria e fixação na parede', concluido: false, categoria: 'Montagem' },
      { id: 'chk_3', titulo: 'Instalação de tampos e bancadas em L', concluido: false, categoria: 'Montagem' },
      { id: 'chk_4', titulo: 'Regulagem de dobradiças slow-motion e corrediças', concluido: false, categoria: 'Acabamento' },
      { id: 'chk_5', titulo: 'Limpeza final pós-obra e aspiração de cavacos', concluido: false, categoria: 'Entrega' }
    ],
    observacoes: 'Cliente solicitou atenção especial ao rodapé da sala de jantar.',
    createdAt: '2026-02-15T10:00:00Z',
    updatedAt: '2026-02-15T10:00:00Z'
  },
  {
    id: 'inst_02',
    empresaId: 'emp_01',
    contratoId: 'ctr_02',
    numeroContrato: '#0043/2026',
    clienteId: 'cli_02',
    clienteNome: 'Dr. Roberto Takahashi',
    enderecoInstalacao: {
      logradouro: 'Av. Brigadeiro Luis Antonio',
      numero: '2340',
      complemento: 'Sala 142',
      bairro: 'Jardim Paulista',
      cidade: 'São Paulo',
      uf: 'SP',
      cep: '01402-000'
    },
    dataHoraAgendamento: '2026-02-19T14:00:00Z',
    montadorId: 'usr_montador',
    montadorNome: 'Rodrigo Barbosa (Montador)',
    status: 'agendada',
    fotos: [],
    checklist: [
      { id: 'chk_201', titulo: 'Conferência de balcão de atendimento e armários', concluido: false, categoria: 'Conferência' },
      { id: 'chk_202', titulo: 'Montagem de nichos suspensos e painel ripado', concluido: false, categoria: 'Montagem' },
      { id: 'chk_203', titulo: 'Testes de gavetas com chave', concluido: false, categoria: 'Acabamento' },
      { id: 'chk_204', titulo: 'Limpeza de bancadas de Corian/MDF', concluido: false, categoria: 'Entrega' }
    ],
    observacoes: 'Instalação comercial no período da tarde após expediente.',
    createdAt: '2026-02-15T11:30:00Z',
    updatedAt: '2026-02-15T11:30:00Z'
  }
];

export const INITIAL_CONTAS_RECEBER: ContaReceber[] = [
  {
    id: 'cr_01',
    empresaId: 'emp_01',
    contratoId: 'ctr_01',
    numeroContrato: '#0042/2026',
    clienteNome: 'Mariana Drummond e Silva',
    valorOriginal: 34500,
    taxaCartaoPercentual: 0,
    valorTaxaCartao: 0,
    valorLiquido: 34500,
    dataVencimento: '2026-02-10T00:00:00Z',
    dataPagamento: '2026-02-10T14:30:00Z',
    status: 'pago',
    formaPagamento: 'PIX à Vista (Ato)',
    numeroParcela: 1,
    totalParcelas: 1
  },
  {
    id: 'cr_02',
    empresaId: 'emp_01',
    contratoId: 'ctr_01',
    numeroContrato: '#0042/2026',
    clienteNome: 'Mariana Drummond e Silva',
    valorOriginal: 34500,
    taxaCartaoPercentual: 2.99,
    valorTaxaCartao: 1031.55,
    valorLiquido: 33468.45,
    dataVencimento: '2026-03-10T00:00:00Z',
    status: 'pendente',
    formaPagamento: 'Cartão de Crédito (10x)',
    numeroParcela: 1,
    totalParcelas: 10
  },
  {
    id: 'cr_03',
    empresaId: 'emp_01',
    contratoId: 'ctr_02',
    numeroContrato: '#0043/2026',
    clienteNome: 'Dr. Roberto Takahashi',
    valorOriginal: 58000,
    taxaCartaoPercentual: 0,
    valorTaxaCartao: 0,
    valorLiquido: 58000,
    dataVencimento: '2026-02-15T00:00:00Z',
    dataPagamento: '2026-02-15T10:00:00Z',
    status: 'pago',
    formaPagamento: 'Transferência Bancária (TED)',
    numeroParcela: 1,
    totalParcelas: 2
  }
];

export const INITIAL_CONTAS_PAGAR: ContaPagar[] = [
  {
    id: 'cp_01',
    empresaId: 'emp_01',
    descricao: 'Fornecedor de Chapas MDF Duratex / Arauco',
    categoria: 'fornecedores',
    valor: 24500,
    dataVencimento: '2026-02-20T00:00:00Z',
    status: 'pendente',
    favorecido: 'Madeireira Central SP Ltda'
  },
  {
    id: 'cp_02',
    empresaId: 'emp_01',
    descricao: 'Aluguel do Showroom & Escritório',
    categoria: 'despesas_fixas',
    valor: 12000,
    dataVencimento: '2026-02-10T00:00:00Z',
    dataPagamento: '2026-02-10T09:00:00Z',
    status: 'pago',
    favorecido: 'Imobiliária Comercial Pinheiros'
  },
  {
    id: 'cp_03',
    empresaId: 'emp_01',
    descricao: 'Impostos Simples Nacional (Faturamento Jan)',
    categoria: 'impostos',
    valor: 8500,
    dataVencimento: '2026-02-28T00:00:00Z',
    status: 'pendente',
    favorecido: 'Receita Federal / DARF'
  }
];

export const INITIAL_COMISSOES: ComissaoRegistro[] = [
  {
    id: 'com_01',
    empresaId: 'emp_01',
    contratoId: 'ctr_01',
    numeroContrato: '#0042/2026',
    beneficiarioNome: 'Juliana Mendes (Vendedora Ouro)',
    tipoBeneficiario: 'vendedor',
    nivelVendedor: 'ouro',
    valorBaseVPL: 69000,
    percentualComissao: 4.5,
    valorComissao: 3105,
    status: 'pago',
    dataVencimento: '2026-02-12T00:00:00Z'
  },
  {
    id: 'com_02',
    empresaId: 'emp_01',
    contratoId: 'ctr_01',
    numeroContrato: '#0042/2026',
    beneficiarioNome: 'Arquiteto Bruno Siqueira (Parceiro RT)',
    tipoBeneficiario: 'parceiro_rt',
    valorBaseVPL: 69000,
    percentualComissao: 5.0,
    valorComissao: 3450,
    status: 'pendente',
    dataVencimento: '2026-02-25T00:00:00Z'
  }
];

export const INITIAL_NOTAS_FISCAIS: NotaFiscalDocumento[] = [
  {
    id: 'nf_01',
    empresaId: 'emp_01',
    contratoId: 'ctr_01',
    numeroContrato: '#0042/2026',
    tipo: 'nfe_produto',
    status: 'autorizada',
    numeroNota: '000142',
    chaveAcesso: '35260248912435000189550010000001421098765432',
    valor: 34500,
    emitidoEm: '2026-02-10T15:00:00Z',
    provedorIntegracao: 'Focus NFe / eNotas API v2 (Produção SEFAZ-SP)',
    xmlUrl: 'https://api.focusnfe.com.br/v2/nfes/35260248912435.xml',
    pdfUrl: 'https://api.focusnfe.com.br/v2/nfes/35260248912435.pdf'
  },
  {
    id: 'nf_02',
    empresaId: 'emp_01',
    contratoId: 'ctr_02',
    numeroContrato: '#0043/2026',
    tipo: 'nfe_produto',
    status: 'rascunho',
    valor: 58000,
    provedorIntegracao: 'Focus NFe / eNotas API v2 (Aguardando Liberação)'
  }
];

export const INITIAL_TICKETS: TicketAssistencia[] = [
  {
    id: 'ast_01',
    empresaId: 'emp_01',
    contratoId: 'ctr_01',
    contratoNumero: '#0042/2026',
    clienteId: 'cli_01',
    clienteNome: 'Mariana Drummond e Silva',
    descricao: 'Ajuste fino de regulagem do amortecedor da porta basculante da torre quente.',
    fotos: ['https://images.unsplash.com/photo-1556911220-e15b29be8c8f?w=600&auto=format&fit=crop&q=80'],
    prioridade: 'normal',
    status: 'agendado',
    tecnicoResponsavel: 'Rodrigo Barbosa',
    dataAgendada: '2026-02-20',
    dataAbertura: '2026-02-14',
    dataResolucao: null,
    historico: [
      { id: 'h1', timestamp: '2026-02-14T10:00:00Z', ator: 'Mariana Drummond', acao: 'Chamado aberto pelo cliente via Portal' },
      { id: 'h2', timestamp: '2026-02-15T09:30:00Z', ator: 'Carlos Admin', acao: 'Triagem concluída e designado para Rodrigo Barbosa' }
    ],
    createdAt: '2026-02-14T10:00:00Z',
    updatedAt: '2026-02-15T09:30:00Z'
  },
  {
    id: 'ast_02',
    empresaId: 'emp_01',
    contratoId: 'ctr_02',
    contratoNumero: '#0041/2026',
    clienteId: 'cli_02',
    clienteNome: 'Dr. Roberto Takahashi',
    descricao: 'Substituição da fita LED do perfil embutido no balcão de recepção do consultório.',
    fotos: ['https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=600&auto=format&fit=crop&q=80'],
    prioridade: 'alta',
    status: 'resolvido',
    tecnicoResponsavel: 'Marcos Vinícius',
    dataAgendada: '2026-02-13',
    dataAbertura: '2026-02-10',
    dataResolucao: '2026-02-13T16:00:00Z',
    historico: [
      { id: 'h3', timestamp: '2026-02-10T14:00:00Z', ator: 'Dr. Roberto Takahashi', acao: 'Chamado aberto' },
      { id: 'h4', timestamp: '2026-02-13T16:00:00Z', ator: 'Marcos Vinícius', acao: 'Reparo concluído e testado com sucesso. Chamado resolvido.' }
    ],
    createdAt: '2026-02-10T14:00:00Z',
    updatedAt: '2026-02-13T16:00:00Z'
  }
];

export const INITIAL_ESTOQUE: MaterialEstoque[] = [
  {
    id: 'mat_01',
    empresaId: 'emp_01',
    codigo: 'MDF-BRANCO-18',
    nome: 'MDF Branco TX 2 Faces 18mm (Guararapes/Duratex)',
    categoria: 'chapa_mdf',
    unidade: 'chapa',
    quantidadeEstoque: 45,
    estoqueMinimo: 10,
    custoUnitario: 220.00,
    precoVendaSugerido: 484.00,
    fornecedor: 'Leo Madeiras SP',
    ultimaAtualizacao: '2026-02-20T10:00:00Z'
  },
  {
    id: 'mat_02',
    empresaId: 'emp_01',
    codigo: 'MDF-CARVALHO-18',
    nome: 'MDF Carvalho Hanover 18mm (Eucatex)',
    categoria: 'chapa_mdf',
    unidade: 'chapa',
    quantidadeEstoque: 28,
    estoqueMinimo: 8,
    custoUnitario: 310.00,
    precoVendaSugerido: 682.00,
    fornecedor: 'Berneck / Distr. Madeiras',
    ultimaAtualizacao: '2026-02-18T14:30:00Z'
  },
  {
    id: 'mat_03',
    empresaId: 'emp_01',
    codigo: 'MDF-GRAFITE-18',
    nome: 'MDF Grafite Matizado 18mm',
    categoria: 'chapa_mdf',
    unidade: 'chapa',
    quantidadeEstoque: 18,
    estoqueMinimo: 6,
    custoUnitario: 295.00,
    precoVendaSugerido: 649.00,
    fornecedor: 'Leo Madeiras SP',
    ultimaAtualizacao: '2026-02-15T09:00:00Z'
  },
  {
    id: 'mat_04',
    empresaId: 'emp_01',
    codigo: 'FITA-BRANCO-22',
    nome: 'Fita de Borda PVC Branca TX 22x0.45mm (Rolo 50m)',
    categoria: 'fita_borda',
    unidade: 'metro',
    quantidadeEstoque: 650,
    estoqueMinimo: 150,
    custoUnitario: 0.45,
    precoVendaSugerido: 1.20,
    fornecedor: 'Proadec Brasil',
    ultimaAtualizacao: '2026-02-10T11:00:00Z'
  },
  {
    id: 'mat_05',
    empresaId: 'emp_01',
    codigo: 'FITA-CARVALHO-35',
    nome: 'Fita de Borda PVC Carvalho 35x1mm (Rolo 50m)',
    categoria: 'fita_borda',
    unidade: 'metro',
    quantidadeEstoque: 320,
    estoqueMinimo: 100,
    custoUnitario: 1.10,
    precoVendaSugerido: 2.80,
    fornecedor: 'Rehau',
    ultimaAtualizacao: '2026-02-12T16:00:00Z'
  },
  {
    id: 'mat_06',
    empresaId: 'emp_01',
    codigo: 'CORRE-TELESCOP-50',
    nome: 'Corrediça Telescópica Galvanizada 50cm com Amortecedor',
    categoria: 'ferragem',
    unidade: 'peca',
    quantidadeEstoque: 120,
    estoqueMinimo: 30,
    custoUnitario: 28.50,
    precoVendaSugerido: 65.00,
    fornecedor: 'Hettich / FGVTN',
    ultimaAtualizacao: '2026-02-22T08:00:00Z'
  },
  {
    id: 'mat_07',
    empresaId: 'emp_01',
    codigo: 'DOBRADICA-SLOW-35',
    nome: 'Dobradiça Caneco 35mm Slow Motion / Amortecimento',
    categoria: 'ferragem',
    unidade: 'peca',
    quantidadeEstoque: 340,
    estoqueMinimo: 80,
    custoUnitario: 6.80,
    precoVendaSugerido: 16.00,
    fornecedor: 'Blum / Hafele',
    ultimaAtualizacao: '2026-02-22T08:10:00Z'
  },
  {
    id: 'mat_08',
    empresaId: 'emp_01',
    codigo: 'PERFIL-LED-EMB',
    nome: 'Perfil Alumínio para LED Embutir com Difusor (Barra 3m)',
    categoria: 'insumo',
    unidade: 'peca',
    quantidadeEstoque: 45,
    estoqueMinimo: 15,
    custoUnitario: 42.00,
    precoVendaSugerido: 95.00,
    fornecedor: 'Glaser Iluminação',
    origemTipo: 'almoxarifado_geral',
    ultimaAtualizacao: '2026-02-19T11:30:00Z'
  },
  {
    id: 'mat_cli_01',
    empresaId: 'emp_01',
    codigo: 'CHP-CLI-01-01',
    nome: 'MDF Louro Freijó 18mm 2F [Cliente: Roberto Campos]',
    categoria: 'chapa_mdf',
    unidade: 'chapa',
    quantidadeEstoque: 0,
    quantidadeNecessaria: 4,
    estoqueMinimo: 0,
    custoUnitario: 320.00,
    precoVendaSugerido: 704.00,
    fornecedor: 'Leo Madeiras SP / Berneck',
    origemTipo: 'projeto_cliente',
    clienteId: 'cli_01',
    clienteNome: 'Roberto Campos',
    projetoId: 'prj_01',
    projetoNome: 'Cozinha Gourmet e Ilha Integrada',
    statusCompra: 'necessario',
    observacoes: 'Necessidade identificada na importação Promob (4 chapas calculadas para frentes e ilha)',
    dataNecessidade: '2026-03-05',
    ultimaAtualizacao: '2026-02-24T09:15:00Z'
  },
  {
    id: 'mat_cli_02',
    empresaId: 'emp_01',
    codigo: 'FIT-CLI-01-02',
    nome: 'Fita de Borda PVC Freijó 22x1mm (Projeto: Cozinha Gourmet)',
    categoria: 'fita_borda',
    unidade: 'metro',
    quantidadeEstoque: 0,
    quantidadeNecessaria: 85,
    estoqueMinimo: 0,
    custoUnitario: 1.85,
    precoVendaSugerido: 4.10,
    fornecedor: 'Proadec Brasil',
    origemTipo: 'projeto_cliente',
    clienteId: 'cli_01',
    clienteNome: 'Roberto Campos',
    projetoId: 'prj_01',
    projetoNome: 'Cozinha Gourmet e Ilha Integrada',
    statusCompra: 'necessario',
    observacoes: '85 metros lineares para acabamento de topos do projeto',
    dataNecessidade: '2026-03-05',
    ultimaAtualizacao: '2026-02-24T09:15:00Z'
  },
  {
    id: 'mat_cli_03',
    empresaId: 'emp_01',
    codigo: 'DOB-CLI-02-01',
    nome: 'Dobradiça Reta 35mm c/ Amortecedor Slow [Mariana Silva]',
    categoria: 'ferragem',
    unidade: 'peca',
    quantidadeEstoque: 16,
    quantidadeNecessaria: 16,
    estoqueMinimo: 0,
    custoUnitario: 8.50,
    precoVendaSugerido: 18.70,
    fornecedor: 'Blum / FGV TN',
    origemTipo: 'projeto_cliente',
    clienteId: 'cli_02',
    clienteNome: 'Mariana Silva',
    projetoId: 'prj_02',
    projetoNome: 'Dormitório Casal & Closet Planejado',
    statusCompra: 'em_estoque',
    observacoes: 'Material recebido no almoxarifado reservado para a montagem',
    dataNecessidade: '2026-03-01',
    ultimaAtualizacao: '2026-02-25T11:00:00Z'
  }
];

export const INITIAL_REGRA_PRECIFICACAO: RegraPrecificacao = {
  id: 'reg_01',
  empresaId: 'emp_01',
  markupPadrao: 2.25,
  margemLucroMinima: 35.0,
  custoM2Corte: 48.00,
  custoMetroFita: 3.50,
  fatorFerragens: 1.35
};

